services:
  servidor1:
    container_name: Servidor1P
    build:
      context: ./Servidor1/BackendDist
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MYSQL_HOST=maestro1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_informacion
      - MYSQL_PORT=3306
    networks:
      - red_distribuida

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: "maestro1,maestro2"
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    networks:
      - red_distribuida

  maestro1:
    container_name: maestro1
    image: mysql:8.0
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog_format=ROW
      --gtid_mode=ON
      --enforce_gtid_consistency=ON
      --log_slave_updates=ON
      --read_only=OFF
      --skip-slave-start
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    ports:
      - 3307:3306
    networks:
      - red_distribuida

  maestro2:
    container_name: maestro2
    image: mysql:8.0
    command:
      --server-id=2
      --log-bin=mysql-bin
      --binlog_format=ROW
      --gtid_mode=ON
      --enforce_gtid_consistency=ON
      --log_slave_updates=ON
      --read_only=OFF
      --skip-slave-start
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    ports:
      - 3308:3306
    networks:
      - red_distribuida

  nginx:
    container_name: nginx1
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - 8080:80
    networks:
      - red_distribuida

networks:
  red_distribuida:
    driver: bridge
