# Etapa 1: Build del frontend
FROM node:20 AS builder

WORKDIR /app

# Copiar dependencias y fuente del frontend
COPY ../Servidor1/Frontend/package*.json ./
RUN npm install

COPY ../Servidor1/Frontend ./
RUN npm run build

# Etapa 2: NGINX que sirve el frontend compilado
FROM nginx:latest

EXPOSE 80

# Copiar configuración personalizada de NGINX
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copiar build generado desde la etapa builder
COPY Servidor1/Frontend/dist /usr/share/nginx/html
